// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfrzuabrfkugxztrihlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhmcnp1YWJyZmt1Z3h6dHJpaGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzQ1MTksImV4cCI6MjA3MjQ1MDUxOX0.35exKzBipVe7REZmi5Xc29jTdY5OjF-xmgAoANz3xyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});